/**
 * Task Intelligence: seed data for TaskTemplate.
 * Templates are stored in the DB and seeded with a fixed number per category.
 */

export const TASK_TEMPLATE_CATEGORIES = [
  "Marketing",
  "Design",
  "Admin",
  "Content",
  "Development",
  "Video/Audio",
  "Automation",
  "Customer Support",
  "Social Media",
  "Analytics",
] as const;

/** Number of templates to seed per category */
export const TASK_TEMPLATES_PER_CATEGORY = 4;

export type TaskTemplateSeed = {
  title: string;
  category: string;
  description: string;
  keyConsiderations: string;
  subtasks: string[];
  deliverables: string[];
  qualityControlChecklist: string[];
};

export function getTaskTemplateSeeds(): TaskTemplateSeed[] {
  return [
    // --- Marketing (4) ---
    {
      title: "Execute Email Marketing Campaign for [PRODUCT/OFFER]",
      category: "Marketing",
      description:
        "Plan, create, and deploy an email marketing campaign to promote a product, service, or special offer. This includes list segmentation, email design, copywriting, A/B testing setup, and post-campaign analysis. Typically requested for product launches, seasonal promotions, or nurture sequences. The VA should understand email best practices, deliverability basics, and how to use the client's email marketing platform effectively.",
      keyConsiderations:
        "Ensure compliance with email regulations (CAN-SPAM, GDPR). Segment lists appropriately to improve relevance and engagement. Test emails across multiple email clients and devices before sending. Monitor deliverability metrics and avoid spam triggers.",
      subtasks: [
        "Define campaign goals, audience, and success metrics",
        "Segment email list based on criteria provided",
        "Draft email copy with compelling subject lines",
        "Design email template matching brand guidelines",
        "Set up A/B test variants if applicable",
        "Configure tracking and UTM parameters",
        "Send test emails and check rendering",
        "Schedule or send campaign at optimal time",
        "Monitor initial performance and deliverability",
        "Compile performance report with recommendations",
      ],
      deliverables: [
        "Campaign strategy brief with goals and KPIs",
        "Segmented email lists with recipient counts",
        "Final email copy and subject line variants",
        "Designed email template (mobile-responsive)",
        "A/B test setup confirmation if used",
        "Tracking and UTM parameter documentation",
        "Test email screenshots across clients",
        "Send confirmation with date and time",
        "Performance report (opens, clicks, conversions)",
        "Recommendations for future campaigns",
      ],
      qualityControlChecklist: [
        "Subject line is compelling and under 50 characters",
        "All links work and point to correct destinations",
        "Unsubscribe link is present and functional",
        "Email renders correctly on mobile and desktop",
        "No broken images or missing content",
        "Personalization tokens work correctly",
        "Spam score checked and acceptable",
        "List segmentation verified for accuracy",
        "Send time optimized for audience timezone",
        "Client approval obtained before sending",
      ],
    },
    {
      title: "Create and Launch Lead Magnet with Landing Page for [OFFER]",
      category: "Marketing",
      description:
        "Design and execute a lead magnet campaign: create a valuable lead magnet (e.g., checklist, template, mini-course), build a dedicated landing page, set up email capture and delivery automation, and promote it through chosen channels. Typically used for list building, product launches, or webinar registration. The VA should understand conversion-focused copy, landing page best practices, and integration between page, email, and CRM.",
      keyConsiderations:
        "Lead magnet must deliver clear value to justify the signup. Landing page should have a single clear CTA. Ensure mobile-responsive design and fast load times. Set up automated delivery so leads receive the asset immediately. Comply with privacy policies and consent capture.",
      subtasks: [
        "Define lead magnet concept and target audience",
        "Create lead magnet content or asset",
        "Write landing page copy (headline, benefits, CTA)",
        "Design or build landing page with form",
        "Set up email automation for delivery",
        "Configure tracking and conversion goals",
        "Add to email sequences if applicable",
        "Prepare promotion copy for social/email",
        "Launch and monitor initial conversions",
        "Report on conversion rate and quality",
      ],
      deliverables: [
        "Lead magnet asset (PDF, video, etc.)",
        "Landing page live and tested",
        "Email automation for instant delivery",
        "Tracking setup (form submissions, source)",
        "Promotion assets (social, email)",
        "Launch confirmation and link",
        "Conversion report with recommendations",
        "A/B test suggestions if applicable",
      ],
      qualityControlChecklist: [
        "Lead magnet delivers on promised value",
        "Landing page loads quickly and is mobile-friendly",
        "Form captures required fields only",
        "Auto-delivery email sends within minutes",
        "Thank-you page or redirect works",
        "Tracking fires correctly",
        "Privacy/consent language present",
        "Links and CTAs tested",
        "Client approval obtained before launch",
      ],
    },
    {
      title: "Plan and Execute [WEBINAR/VIRTUAL EVENT] Marketing Campaign",
      category: "Marketing",
      description:
        "Develop and implement a complete marketing strategy for a webinar or virtual event. This includes creating promotional materials, setting up registration pages, managing email sequences (invitation, reminders, follow-up), coordinating with speakers, and tracking attendance metrics. Typically requested for thought leadership events, product demos, or educational sessions. The VA should understand event marketing funnels and multi-channel promotion.",
      keyConsiderations:
        "Start promotion 2-4 weeks before event date. Send multiple reminder emails to boost attendance rates. Create different messaging for different audience segments. Have a clear post-event follow-up strategy. Track registration-to-attendance conversion rates.",
      subtasks: [
        "Define event goals, target audience, and messaging",
        "Create event registration landing page",
        "Design promotional graphics for social and email",
        "Write invitation and promotional email copy",
        "Set up automated reminder email sequence",
        "Create social media promotion calendar",
        "Coordinate speaker bios and headshots",
        "Set up post-event survey and thank you sequence",
        "Monitor registration numbers and adjust promotion",
        "Compile attendance and engagement report",
      ],
      deliverables: [
        "Event strategy document with timeline",
        "Registration landing page with form",
        "Promotional email templates (invite, reminders)",
        "Social media graphics and copy",
        "Speaker coordination checklist",
        "Automated email sequence setup",
        "Event day checklist and timeline",
        "Post-event survey",
        "Follow-up email sequence for attendees and no-shows",
        "Performance report with attendance metrics",
      ],
      qualityControlChecklist: [
        "Registration page tested across devices",
        "All promotional copy is error-free and on-brand",
        "Email sequence timing is optimal",
        "Calendar invites sent to registrants",
        "Speaker materials collected and approved",
        "Reminder emails scheduled correctly",
        "Post-event assets ready before event",
        "Tracking pixels implemented correctly",
        "Client approval on all public-facing materials",
        "Backup plans documented for technical issues",
      ],
    },
    {
      title:
        "Conduct Competitor Analysis and Market Research for [PRODUCT/NICHE]",
      category: "Marketing",
      description:
        "Research and analyze competitors in the client's market to identify positioning opportunities, pricing strategies, marketing tactics, and market gaps. This includes identifying key competitors, analyzing their online presence, reviewing customer feedback, and compiling actionable insights. Typically requested before product launches, rebranding, or strategic planning. The VA should be skilled at research, data synthesis, and presenting findings clearly.",
      keyConsiderations:
        "Focus on actionable insights, not just data collection. Look at both direct and indirect competitors. Include pricing, positioning, content strategy, and customer sentiment. Respect ethical boundaries—no deceptive practices. Present findings in an easy-to-digest format.",
      subtasks: [
        "Identify 5-10 key competitors in the space",
        "Analyze competitor websites and messaging",
        "Review competitor social media presence",
        "Research competitor pricing and offerings",
        "Collect customer reviews and sentiment analysis",
        "Identify competitor content and SEO strategies",
        "Map out competitor strengths and weaknesses",
        "Identify market gaps and opportunities",
        "Compile findings into structured report",
        "Present strategic recommendations",
      ],
      deliverables: [
        "Competitor list with website and contact info",
        "Competitive positioning matrix",
        "Pricing comparison chart",
        "Social media presence analysis",
        "Customer sentiment summary by competitor",
        "Content and SEO strategy overview",
        "SWOT analysis for each major competitor",
        "Market gaps and opportunities identified",
        "Strategic recommendations report",
        "Executive summary presentation",
      ],
      qualityControlChecklist: [
        "All competitor data is current and accurate",
        "Analysis covers all requested dimensions",
        "Sources are credible and documented",
        "Insights are actionable and strategic",
        "Visual aids enhance understanding",
        "No unethical research methods used",
        "Recommendations align with client goals",
        "Report is well-organized and professional",
        "Data presented objectively without bias",
        "Client can act on findings immediately",
      ],
    },

    // --- Design (4) ---
    {
      title: "Design [MARKETING COLLATERAL] for [CAMPAIGN/PURPOSE]",
      category: "Design",
      description:
        "Create visual marketing materials such as social media graphics, infographics, presentations, brochures, or ads. This includes understanding the brief, developing concepts, creating designs in brand style, and delivering final files in required formats. Typically requested for campaigns, events, or ongoing brand content needs. The VA should be proficient in design tools and understand visual hierarchy, typography, and brand consistency.",
      keyConsiderations:
        "Adhere strictly to brand guidelines (colors, fonts, logos). Ensure designs are optimized for their intended platform or medium. Consider accessibility (contrast, readability). Obtain proper licensing for any stock images or fonts used.",
      subtasks: [
        "Review design brief and gather requirements",
        "Collect brand assets and guidelines",
        "Research design trends for the medium",
        "Create initial design concepts or mockups",
        "Present concepts to client for feedback",
        "Revise design based on feedback",
        "Finalize design with all required elements",
        "Prepare files in all requested formats",
        "Organize and label files clearly",
        "Deliver with usage guidelines if needed",
      ],
      deliverables: [
        "Initial design concepts (2-3 options)",
        "Final design in editable source format",
        "Export files in required formats (PNG, PDF, etc.)",
        "Web-optimized versions if applicable",
        "Print-ready files with bleed if for print",
        "Font and asset documentation",
        "Color codes and specifications",
        "Usage guidelines or template instructions",
        "Organized file folder with clear naming",
        "Design revision history if requested",
      ],
      qualityControlChecklist: [
        "Design follows brand guidelines accurately",
        "All text is spelled correctly and legible",
        "Images are high resolution and properly licensed",
        "Color contrast meets accessibility standards",
        "Design works at all required sizes",
        "Files are in correct formats and dimensions",
        "No placeholder text or images remain",
        "Client feedback incorporated fully",
        "Files are properly named and organized",
        "Final approval received from client",
      ],
    },
    {
      title: "Create Presentation Deck for [MEETING/PITCH/PROJECT]",
      category: "Design",
      description:
        "Design a professional presentation (e.g., PowerPoint, Google Slides, Keynote) for a specific purpose: investor pitch, sales deck, internal review, or webinar. Includes structure, copy, visuals, charts, and speaker notes. The VA should understand narrative flow, visual hierarchy, and the client's brand so the deck is both on-brand and persuasive.",
      keyConsiderations:
        "Match slide count and depth to audience and time available. Use consistent branding (colors, fonts, logo). Keep text minimal; let visuals support the story. Ensure charts and data are accurate and cited. Export in requested format and check compatibility with client's software.",
      subtasks: [
        "Clarify purpose, audience, and key messages",
        "Create outline and slide structure",
        "Draft copy for each slide",
        "Source or create visuals and graphics",
        "Build slides with consistent styling",
        "Add charts or data visualizations",
        "Write speaker notes if requested",
        "Review for flow and clarity",
        "Apply client feedback and finalize",
        "Export in required format(s)",
      ],
      deliverables: [
        "Presentation file (PPTX, etc.)",
        "PDF version for sharing",
        "Speaker notes document if applicable",
        "Source file for future edits",
        "Image/asset folder",
        "Brand-compliant design",
      ],
      qualityControlChecklist: [
        "All text proofread and accurate",
        "Charts and numbers match sources",
        "Brand guidelines followed",
        "No broken images or links",
        "Slides flow logically",
        "File opens in client's preferred tool",
        "Client sign-off obtained",
      ],
    },
    {
      title: "Design Brand Identity Package for [BUSINESS/PROJECT]",
      category: "Design",
      description:
        "Create a complete brand identity system including logo design, color palette, typography, and brand guidelines. This includes initial concept development, refinement based on feedback, and delivery of all brand assets in multiple formats. Typically requested for new businesses, rebrands, or sub-brands. The VA should understand branding principles, logo design best practices, and how to create scalable identity systems.",
      keyConsiderations:
        "Ensure logo works in various sizes and applications (web, print, merchandise). Design for scalability and versatility. Consider color psychology and target audience. Provide clear usage guidelines to maintain brand consistency. Deliver vector formats for future flexibility.",
      subtasks: [
        "Conduct brand discovery call to understand vision",
        "Research industry and competitor branding",
        "Develop mood board and style direction",
        "Create 3-5 initial logo concepts",
        "Present concepts with rationale",
        "Refine selected concept based on feedback",
        "Develop full color palette with codes",
        "Select primary and secondary typography",
        "Create brand guidelines document",
        "Deliver all assets in multiple formats",
      ],
      deliverables: [
        "Final logo in vector formats (AI, EPS, SVG)",
        "Logo variations (full color, black, white, icon)",
        "Color palette with HEX, RGB, CMYK codes",
        "Typography system with font files",
        "Brand guidelines document (PDF)",
        "Logo usage examples and don'ts",
        "Social media profile images",
        "Business card design template",
        "Letterhead and email signature templates",
        "Brand asset library organized by type",
      ],
      qualityControlChecklist: [
        "Logo is unique and memorable",
        "Design works at small and large sizes",
        "Colors are accessible and print-friendly",
        "Fonts are properly licensed",
        "All file formats delivered as promised",
        "Brand guidelines are comprehensive",
        "Usage examples cover key applications",
        "Client owns all rights to final designs",
        "Files properly organized and labeled",
        "Final approval and sign-off obtained",
      ],
    },
    {
      title: "Create [PRINT MATERIALS] Design for [EVENT/CAMPAIGN]",
      category: "Design",
      description:
        "Design print marketing materials such as flyers, posters, brochures, business cards, or banners. This includes layout design, ensuring print specifications are met, preparing print-ready files with bleeds and crop marks, and coordinating with print vendors if needed. Typically requested for events, tradeshows, retail displays, or offline marketing. The VA should understand print production requirements and CMYK color workflows.",
      keyConsiderations:
        'Work in CMYK color mode for accurate print colors. Include proper bleed (usually 0.125") and safety margins. Use high-resolution images (300 DPI minimum). Verify paper size, finish, and quantity with client. Request print proofs before final production run.',
      subtasks: [
        "Confirm print specifications and quantities",
        "Set up document with correct dimensions and bleed",
        "Design layout following brand guidelines",
        "Optimize images for print resolution",
        "Add crop marks and printer's marks",
        "Convert colors to CMYK if needed",
        "Preflight file for print issues",
        "Export print-ready PDF with settings",
        "Send proof to client for approval",
        "Coordinate with printer or deliver files",
      ],
      deliverables: [
        "Print-ready PDF with bleeds and marks",
        "Editable source file for future updates",
        "Digital proof for client review",
        "Print specifications document",
        "Color reference guide",
        "Printer communication and quote if applicable",
      ],
      qualityControlChecklist: [
        "Document set up with correct dimensions",
        'Bleed area extends 0.125" beyond trim',
        "All images are 300 DPI or higher",
        "Colors converted to CMYK accurately",
        "Fonts embedded or outlined",
        "No RGB colors or spot colors (unless specified)",
        "Crop marks and bleed marks present",
        "File passes preflight check",
        "Client approved final proof",
        "Printer confirmed they can work with files",
      ],
    },

    // --- Admin (4) ---
    {
      title: "Manage Calendar and Schedule [MEETINGS/APPOINTMENTS]",
      category: "Admin",
      description:
        "Coordinate and manage the client's calendar, including scheduling meetings, sending invitations, managing conflicts, and ensuring all participants are prepared. This includes booking video calls, coordinating across time zones, sending reminders, and rescheduling as needed. Typically requested by executives, consultants, or busy professionals who need calendar support. The VA should be detail-oriented and proactive in anticipating scheduling needs.",
      keyConsiderations:
        "Respect time zone differences and preferred meeting times. Build in buffer time between meetings. Confirm attendance before meetings. Maintain confidentiality of calendar contents and meeting purposes.",
      subtasks: [
        "Review calendar for conflicts and availability",
        "Coordinate with attendees to find suitable times",
        "Send calendar invitations with agenda and details",
        "Book video conferencing links if needed",
        "Add time zone information for global meetings",
        "Send reminder emails 24 hours before meetings",
        "Prepare briefing materials or agendas",
        "Handle reschedules and communicate changes",
        "Block focus time or prep time as requested",
        "Update recurring meetings and templates",
      ],
      deliverables: [
        "Updated calendar with all meetings scheduled",
        "Calendar invitations sent to all participants",
        "Video conferencing links for virtual meetings",
        "Meeting agendas or briefing documents",
        "Time zone conversion reference if needed",
        "Reminder confirmations sent",
        "Rescheduling confirmations if applicable",
        "Weekly calendar summary for client review",
        "Contact list for regular meeting attendees",
        "Calendar management process documentation",
      ],
      qualityControlChecklist: [
        "All meeting times confirmed with attendees",
        "No double-bookings or conflicts present",
        "Video links tested and working",
        "Invitations include all necessary information",
        "Time zones clearly indicated",
        "Reminders scheduled appropriately",
        "Client preferences honored (buffer time, etc.)",
        "Recurring meetings updated as needed",
        "Cancellations communicated promptly",
        "Calendar access and permissions verified",
      ],
    },
    {
      title: "Prepare Monthly Expense Report and Reconcile [ACCOUNTS]",
      category: "Admin",
      description:
        "Gather expense data from receipts, cards, and accounts; categorize spending; reconcile against budgets or statements; and produce a clear monthly expense report. May include coding to cost centers, flagging variances, and preparing summaries for leadership. Typically requested by small business owners or department heads. The VA should be detail-oriented and comfortable with spreadsheets and basic accounting concepts.",
      keyConsiderations:
        "Classify expenses consistently with client's chart of accounts or categories. Keep receipts and documentation organized. Respect confidentiality of financial data. Clarify approval workflows and deadlines. Flag unusual or duplicate transactions.",
      subtasks: [
        "Collect receipts and transaction exports",
        "Import or enter data into tracking sheet",
        "Categorize each expense correctly",
        "Reconcile against bank/credit statements",
        "Compare to budget if provided",
        "Flag variances or anomalies",
        "Draft summary and commentary",
        "Prepare report in requested format",
        "Archive supporting documents",
        "Submit for review by deadline",
      ],
      deliverables: [
        "Monthly expense report (spreadsheet or PDF)",
        "Categorized transaction list",
        "Reconciliation notes",
        "Variance or exception summary",
        "Organized receipt/attachment folder",
        "Recommendations if requested",
      ],
      qualityControlChecklist: [
        "All transactions accounted for",
        "Categories applied consistently",
        "Reconciliation balances",
        "No duplicate entries",
        "Confidentiality maintained",
        "Client approval process followed",
      ],
    },
    {
      title: "Organize and Maintain [DOCUMENT/FILE] Management System",
      category: "Admin",
      description:
        "Set up or reorganize digital file storage systems (Google Drive, Dropbox, SharePoint) with logical folder structures, naming conventions, and permission settings. This includes migrating files, archiving old content, setting up shared folders, and creating documentation for the system. Typically requested during onboarding, after mergers, or when existing systems are chaotic. The VA should understand information architecture and file organization best practices.",
      keyConsiderations:
        "Create a system that scales as files grow. Use consistent naming conventions that make search easy. Set appropriate permission levels to protect sensitive information. Document the system so others can maintain it. Plan for regular maintenance and cleanup.",
      subtasks: [
        "Audit existing file structure and identify issues",
        "Design new folder hierarchy and naming system",
        "Create master folder structure",
        "Sort and migrate files to new locations",
        "Remove duplicates and outdated files",
        "Archive old files with clear labeling",
        "Set up sharing permissions and access levels",
        "Create folder templates for recurring needs",
        "Document file organization system",
        "Train client and team on new system",
      ],
      deliverables: [
        "Organized folder structure in cloud storage",
        "File naming convention guide",
        "Permission matrix showing who accesses what",
        "Archive folder with dated backup",
        "Templates for common document types",
        "File organization documentation",
        "Quick reference guide for team",
        "Maintenance schedule recommendations",
      ],
      qualityControlChecklist: [
        "Folder structure is logical and intuitive",
        "All files properly categorized and labeled",
        "No duplicate or orphaned files",
        "Naming conventions applied consistently",
        "Permissions set appropriately for each folder",
        "Archive clearly separated from active files",
        "Documentation is clear and comprehensive",
        "Team understands how to use system",
        "Search functionality tested and working",
        "Client satisfied with organization",
      ],
    },
    {
      title: "Book Travel Arrangements for [TRIP/EVENT]",
      category: "Admin",
      description:
        "Research and book complete travel arrangements including flights, accommodation, ground transportation, and any special requirements. This includes finding best options within budget, coordinating itineraries, managing changes, and creating comprehensive travel documents. Typically requested for business trips, speaking engagements, or corporate events. The VA should understand travel booking platforms, loyalty programs, and travel policies.",
      keyConsiderations:
        "Book within company travel policy and budget. Consider traveler preferences and frequent flyer programs. Build in buffer time for connections and appointments. Get travel insurance when appropriate. Have contingency plans for delays or cancellations.",
      subtasks: [
        "Gather trip requirements and preferences",
        "Research flight options within budget",
        "Compare hotel options near destination",
        "Book flights and accommodations",
        "Arrange ground transportation (rental car, transfers)",
        "Add loyalty program numbers to reservations",
        "Purchase travel insurance if requested",
        "Create detailed itinerary with confirmations",
        "Set up check-in reminders",
        "Provide emergency contact information",
      ],
      deliverables: [
        "Flight confirmations with seat assignments",
        "Hotel reservations with addresses",
        "Ground transportation details",
        "Complete travel itinerary document",
        "Boarding passes (when available)",
        "Maps and directions to key locations",
        "Emergency contacts and resources",
        "Expense tracking sheet for trip",
        "Mobile itinerary in accessible format",
        "Post-trip receipt compilation",
      ],
      qualityControlChecklist: [
        "All bookings confirmed and paid",
        "Loyalty numbers added to reservations",
        "Travel times allow for connections",
        "Accommodation location is convenient",
        "Ground transportation arranged for all legs",
        "Traveler has all confirmation numbers",
        "Itinerary includes addresses and phone numbers",
        "Travel insurance purchased if required",
        "Check-in reminders scheduled",
        "Client approved all arrangements",
      ],
    },

    // --- Content (4) ---
    {
      title: "Write and Optimize Blog Post on [TOPIC]",
      category: "Content",
      description:
        "Research, write, and optimize a blog post on a specified topic. This includes keyword research, outline creation, writing engaging content, SEO optimization, adding internal/external links, and formatting for web. Typically requested as part of content marketing strategy to drive organic traffic and establish thought leadership. The VA should understand SEO basics, the client's target audience, and how to write compelling web content.",
      keyConsiderations:
        "Focus on providing genuine value to readers, not just keyword stuffing. Use proper heading hierarchy (H1, H2, H3). Include credible sources and data. Optimize meta description and title tag. Ensure content aligns with the client's brand voice and expertise.",
      subtasks: [
        "Conduct keyword research for the topic",
        "Research topic and gather credible sources",
        "Create detailed outline with headers",
        "Write engaging introduction and conclusion",
        "Develop body content with clear sections",
        "Add internal links to related content",
        "Include external links to authoritative sources",
        "Optimize for target keywords naturally",
        "Write SEO title and meta description",
        "Format content with images and proper styling",
      ],
      deliverables: [
        "Keyword research report with target terms",
        "Content outline with main points",
        "Complete blog post (800-2000 words)",
        "SEO-optimized title tag (under 60 characters)",
        "Meta description (under 160 characters)",
        "Suggested featured image or graphics",
        "Internal and external link recommendations",
        "Image alt text suggestions",
        "Content in CMS-ready format or HTML",
        "Performance tracking setup (if requested)",
      ],
      qualityControlChecklist: [
        "Content provides clear value to target audience",
        "Primary keyword used naturally throughout",
        "Heading hierarchy is logical and SEO-friendly",
        "All facts and statistics are sourced",
        "Internal links point to relevant content",
        "External links are credible and working",
        "No grammatical or spelling errors",
        "Meta title and description compelling",
        "Images have descriptive alt text",
        "Content matches brand voice and style",
      ],
    },
    {
      title: "Write and Send [NEWSLETTER/DIGEST] for [AUDIENCE]",
      category: "Content",
      description:
        "Plan, write, and send a regular newsletter or email digest. Includes topic selection, writing engaging copy, formatting for email, scheduling, and optional performance summary. Typically used for nurturing leads, staying top-of-mind with customers, or sharing updates. The VA should understand email copywriting, the client's voice, and the chosen email platform.",
      keyConsiderations:
        "Keep subject lines clear and engaging. Balance value (useful content) with promotion. Maintain consistent send cadence. Segment lists when relevant. Include unsubscribe and physical address for compliance.",
      subtasks: [
        "Confirm theme, CTA, and send date",
        "Draft subject line options",
        "Write headline and body copy",
        "Add links and CTAs",
        "Format in email builder",
        "Preview and test on devices",
        "Schedule or send at agreed time",
        "Monitor opens/clicks if requested",
        "Summarize performance for client",
      ],
      deliverables: [
        "Final copy (in platform or doc)",
        "Subject line(s) used",
        "Send confirmation and metrics",
        "Short performance summary",
      ],
      qualityControlChecklist: [
        "Subject line under 50 characters",
        "All links work",
        "Unsubscribe and address present",
        "Mobile preview checked",
        "Sent on schedule",
      ],
    },
    {
      title: "Create Content Calendar for [CHANNEL] for [TIMEFRAME]",
      category: "Content",
      description:
        "Plan and organize a content calendar for blog, social media, email, or multiple channels. This includes topic ideation, content types, publishing schedule, content assignments, and theme alignment with marketing goals. Typically requested quarterly or monthly to maintain consistent content output. The VA should understand content strategy, editorial planning, and how different content types support business goals.",
      keyConsiderations:
        "Align content with business goals and seasonal events. Mix educational, promotional, and entertaining content. Consider content production timelines and approval processes. Build in flexibility for timely or reactive content. Coordinate across channels to avoid repetition.",
      subtasks: [
        "Review content goals and audience insights",
        "Conduct content gap analysis",
        "Brainstorm topics and content ideas",
        "Define content types and formats",
        "Map topics to publishing dates",
        "Assign content to team members or freelancers",
        "Note key dates and seasonal themes",
        "Create production timeline with deadlines",
        "Build in review and approval stages",
        "Export calendar in shareable format",
      ],
      deliverables: [
        "Content calendar spreadsheet or tool",
        "Topic list with descriptions",
        "Publishing schedule with dates",
        "Content assignment tracker",
        "Production timeline with milestones",
        "Template for recurring content types",
        "Key date and theme reference",
        "Content brief template",
      ],
      qualityControlChecklist: [
        "Calendar covers entire requested timeframe",
        "Topics align with business goals",
        "Content mix is balanced and varied",
        "All dates and deadlines are realistic",
        "Responsibilities clearly assigned",
        "Production timeline allows for quality",
        "Seasonal and industry events included",
        "Calendar format is accessible to all stakeholders",
        "Client approved overall content strategy",
        "System for updating calendar established",
      ],
    },
    {
      title: "Write Case Study or Success Story for [CLIENT/PROJECT]",
      category: "Content",
      description:
        "Interview client or stakeholders and write a compelling case study showcasing results achieved. This includes gathering data, conducting interviews, structuring the narrative (challenge, solution, results), adding quotes and statistics, and formatting for publication. Typically used for sales materials, website content, or portfolio pieces. The VA should be skilled at storytelling, interviewing, and presenting data persuasively.",
      keyConsiderations:
        "Get client approval before publishing. Use specific, quantifiable results when possible. Structure story to resonate with similar prospects. Include compelling quotes that humanize the story. Follow privacy and confidentiality agreements.",
      subtasks: [
        "Schedule interview with client or stakeholders",
        "Prepare interview questions focused on results",
        "Conduct interview and record key insights",
        "Gather supporting data and metrics",
        "Structure story with clear narrative arc",
        "Write draft highlighting challenge and solution",
        "Incorporate quotes and statistics",
        "Add visuals or charts if applicable",
        "Submit draft to client for approval",
        "Finalize and format for publication",
      ],
      deliverables: [
        "Interview notes and recording",
        "Complete case study (800-1500 words)",
        "Pull quotes formatted for design",
        "Key metrics and results summary",
        "Before/after comparison if applicable",
        "Client testimonial quote",
        "Suggested images or graphics",
        "Multiple format versions (web, PDF)",
        "Client approval documentation",
        "Promotion plan for case study",
      ],
      qualityControlChecklist: [
        "Story follows clear narrative structure",
        "Results are specific and quantifiable",
        "Quotes are authentic and compelling",
        "All data and claims verified",
        "Client approved all content",
        "Confidential information protected",
        "Story resonates with target audience",
        "No grammatical or factual errors",
        "Formatted professionally and on-brand",
        "Ready for immediate publication",
      ],
    },

    // --- Development (4) ---
    {
      title: "Build Custom [FEATURE/INTEGRATION] for [WEBSITE/APP]",
      category: "Development",
      description:
        "Develop a custom feature, functionality, or integration for a website or application. This could include contact forms, payment processing, API integrations, custom calculators, or database connections. Includes planning, coding, testing, and deployment. Typically requested when standard plugins or tools don't meet specific business needs. The VA should have coding skills and understand web development best practices.",
      keyConsiderations:
        "Write clean, well-commented code for future maintenance. Test thoroughly across browsers and devices. Follow security best practices, especially for forms and data handling. Document the implementation for the client or future developers.",
      subtasks: [
        "Gather detailed requirements and specifications",
        "Plan architecture and technical approach",
        "Set up development environment and version control",
        "Write code following best practices",
        "Implement error handling and validation",
        "Test functionality across browsers/devices",
        "Integrate with existing systems if applicable",
        "Write technical documentation",
        "Deploy to staging for client review",
        "Deploy to production after approval",
      ],
      deliverables: [
        "Technical specification document",
        "Source code with clear comments",
        "Version control repository access",
        "Working feature on staging environment",
        "Browser and device compatibility report",
        "Technical documentation for maintenance",
        "User guide if feature is client-facing",
        "Test results and QA report",
        "Production deployment confirmation",
        "Post-launch monitoring plan",
      ],
      qualityControlChecklist: [
        "Code follows best practices and standards",
        "All functions work as specified",
        "Error handling covers edge cases",
        "Security vulnerabilities addressed",
        "Works across major browsers",
        "Mobile responsive if applicable",
        "Load time is acceptable",
        "Documentation is complete and clear",
        "Client testing and approval completed",
        "Backup and rollback plan in place",
      ],
    },
    {
      title: "Set Up and Configure [TOOL/PLATFORM] for [PURPOSE]",
      category: "Development",
      description:
        "Install, configure, and optionally customize a software tool or platform (e.g., CMS, CRM, form builder, analytics) to meet the client's workflow. Includes account setup, integrations, permissions, and basic training or documentation. Requested when onboarding new tools or changing processes. The VA should be comfortable with SaaS admin panels and common integrations.",
      keyConsiderations:
        "Follow security best practices (strong passwords, minimal permissions). Document login and configuration for the client. Test core flows before handoff. Confirm data ownership and backup options.",
      subtasks: [
        "Confirm tool, plan, and requirements",
        "Create or access admin account",
        "Configure core settings and branding",
        "Set up users and permissions",
        "Connect integrations (email, CRM, etc.)",
        "Create templates or default content if needed",
        "Test main workflows",
        "Document setup and usage",
        "Hand off with training or walkthrough",
      ],
      deliverables: [
        "Configured tool ready for use",
        "Admin and user access documented",
        "Short setup/usage guide",
        "Integration checklist",
      ],
      qualityControlChecklist: [
        "All required settings completed",
        "Integrations tested",
        "Access and credentials documented securely",
        "Client can perform key tasks",
      ],
    },
    {
      title: "Fix Bugs and Issues in [WEBSITE/APPLICATION]",
      category: "Development",
      description:
        "Identify, diagnose, and fix bugs or technical issues in existing websites or applications. This includes reproducing errors, debugging code, implementing fixes, testing solutions, and preventing similar issues. Typically requested when users report problems or during routine maintenance. The VA should have strong debugging skills and systematic problem-solving approach.",
      keyConsiderations:
        "Document the issue thoroughly before fixing. Test fixes in staging before production. Check for related issues that might have same root cause. Implement fixes that don't break existing functionality. Keep client updated on progress.",
      subtasks: [
        "Review bug reports and gather details",
        "Reproduce issue in testing environment",
        "Identify root cause of the problem",
        "Develop fix with minimal side effects",
        "Test fix across affected scenarios",
        "Check for regression in other areas",
        "Document what was changed and why",
        "Deploy fix to staging for verification",
        "Get client approval on fix",
        "Deploy to production and monitor",
      ],
      deliverables: [
        "Bug report documentation",
        "Root cause analysis",
        "Code changes with comments",
        "Test results confirming fix",
        "Before/after screenshots or videos",
        "Deployment notes",
        "Prevention recommendations",
        "Updated code repository",
      ],
      qualityControlChecklist: [
        "Issue fully reproduced before fixing",
        "Root cause properly identified",
        "Fix addresses issue completely",
        "No new bugs introduced",
        "Testing covers edge cases",
        "Code changes are minimal and focused",
        "Documentation explains changes clearly",
        "Client verified fix works",
        "Changes deployed safely",
        "Monitoring in place post-deployment",
      ],
    },
    {
      title: "Optimize Website Performance and Speed for [SITE]",
      category: "Development",
      description:
        "Audit and improve website loading speed and performance through various optimization techniques. This includes image compression, code minification, caching setup, database optimization, and CDN configuration. Typically requested when site is slow or to improve SEO rankings. The VA should understand web performance metrics and optimization tools.",
      keyConsiderations:
        "Run baseline performance tests before starting. Prioritize changes with biggest impact. Don't sacrifice functionality for speed. Test thoroughly after each optimization. Monitor performance over time, not just one-time fixes.",
      subtasks: [
        "Run performance audit (PageSpeed, GTmetrix)",
        "Identify main performance bottlenecks",
        "Compress and optimize all images",
        "Minify CSS, JavaScript, and HTML",
        "Enable browser caching",
        "Implement lazy loading for images",
        "Optimize database queries if applicable",
        "Set up CDN for static assets",
        "Remove unused plugins or scripts",
        "Test performance improvements",
      ],
      deliverables: [
        "Initial performance audit report",
        "Optimization recommendations prioritized",
        "Compressed image assets",
        "Minified code files",
        "Caching configuration documentation",
        "CDN setup guide",
        "Before/after performance comparison",
        "Post-optimization audit report",
        "Ongoing monitoring recommendations",
      ],
      qualityControlChecklist: [
        "Baseline metrics documented",
        "All images properly compressed",
        "Code minification not breaking functionality",
        "Caching working across browsers",
        "CDN properly configured",
        "Page load time improved measurably",
        "Mobile performance also improved",
        "No broken features after optimization",
        "Performance gains sustained over time",
        "Client satisfied with speed improvements",
      ],
    },

    // --- Video/Audio (4) ---
    {
      title: "Edit [VIDEO/PODCAST] Episode for [SERIES/CHANNEL]",
      category: "Video/Audio",
      description:
        "Edit raw video or audio content into a polished final product ready for publishing. This includes cutting unnecessary sections, adding intro/outro, incorporating graphics or B-roll, color correction, sound mixing, and exporting in the required format. Typically requested for YouTube videos, podcasts, online courses, or marketing videos. The VA should be proficient with editing software and understand pacing, storytelling, and platform requirements.",
      keyConsiderations:
        "Maintain consistent audio levels throughout. Follow the client's style guide for intros, outros, and graphics. Export in the correct format and resolution for the destination platform. Keep project files organized for future revisions.",
      subtasks: [
        "Import and organize raw footage or audio files",
        "Review content and identify sections to cut",
        "Trim and arrange clips in logical sequence",
        "Add intro, outro, and transition elements",
        "Incorporate graphics, text overlays, or B-roll",
        "Color grade video or balance audio levels",
        "Add background music or sound effects",
        "Export in required format and resolution",
        "Upload to client's platform or storage",
        "Archive project files for future edits",
      ],
      deliverables: [
        "Edited video/audio in final format",
        "Thumbnail or cover art if requested",
        "Transcript or captions file if needed",
        "Multiple format exports if required",
        "Project file for future edits",
        "Asset folder with all media used",
        "Metadata (title, description, tags)",
        "Preview link for client approval",
        "Upload confirmation to platform",
        "Backup of final and project files",
      ],
      qualityControlChecklist: [
        "All cuts are smooth and intentional",
        "Audio levels consistent throughout",
        "No background noise or audio artifacts",
        "Video quality and resolution appropriate",
        "Branding elements match style guide",
        "Transitions are smooth and not distracting",
        "Text is legible and spell-checked",
        "Export settings match platform requirements",
        "Client approval obtained before publishing",
        "Files properly backed up and archived",
      ],
    },
    {
      title:
        "Create Short-Form Video Clips from [LONG-FORM CONTENT] for [PLATFORM]",
      category: "Video/Audio",
      description:
        "Identify highlight moments from a long-form video (webinar, podcast, interview) and edit them into short, platform-optimized clips for social (e.g., YouTube Shorts, Instagram Reels, TikTok). Includes selecting segments, adding captions, formatting for aspect ratio and length, and exporting. Typically requested for repurposing content and increasing reach. The VA should understand platform specs and hook-driven editing.",
      keyConsiderations:
        "Respect platform limits (length, aspect ratio, file size). Use captions for accessibility and sound-off viewing. Hook in the first few seconds. Credit or brand consistently. Check music and rights for reuse.",
      subtasks: [
        "Review full video and note timestamps",
        "Select 3–5 clip-worthy segments",
        "Edit each clip to length and ratio",
        "Add captions or subtitles",
        "Add intro/outro or branding",
        "Export in platform specs",
        "Upload or deliver files",
        "Provide suggested captions and hashtags",
      ],
      deliverables: [
        "Short-form clips (specified count)",
        "Caption/hashtag suggestions",
        "Source timestamps for reference",
      ],
      qualityControlChecklist: [
        "Length and ratio match platform",
        "Captions accurate and readable",
        "Audio levels consistent",
        "Branding present where agreed",
        "Files named and organized",
      ],
    },
    {
      title: "Record and Produce Podcast Episode on [TOPIC]",
      category: "Video/Audio",
      description:
        "Handle full podcast production from recording to publishing. This includes setting up recording equipment, conducting or facilitating the interview/discussion, editing audio, adding intro/outro music, creating show notes, and uploading to podcast platforms. Typically requested for regular podcast series or special episodes. The VA should understand podcast recording best practices and audio production.",
      keyConsiderations:
        "Test audio equipment before recording. Use backup recording methods. Brief guests on format and expectations. Edit out long pauses and filler words while keeping natural flow. Optimize audio for spoken word (not music).",
      subtasks: [
        "Coordinate recording time with guest(s)",
        "Prepare interview questions or discussion outline",
        "Set up and test recording equipment",
        "Record episode with backup recording",
        "Edit audio for clarity and pacing",
        "Add intro, outro, and music beds",
        "Normalize audio levels",
        "Write show notes and timestamps",
        "Create episode artwork if needed",
        "Upload to podcast hosting platform",
      ],
      deliverables: [
        "Final edited podcast episode (MP3)",
        "Show notes with timestamps",
        "Episode description and keywords",
        "Custom episode artwork if applicable",
        "Transcript if requested",
        "Audiogram clips for social promotion",
        "Upload confirmation to hosting platform",
        "RSS feed verification",
        "Project file for future reference",
      ],
      qualityControlChecklist: [
        "Audio quality is clear and professional",
        "No technical glitches or dropouts",
        "Intro and outro properly placed",
        "Music levels don't overpower speech",
        "Show notes are accurate and helpful",
        "Episode metadata complete",
        "Uploaded to all distribution platforms",
        "Audio levels meet platform specifications",
        "Client approved final edit",
        "Files archived and backed up",
      ],
    },
    {
      title: "Create Video Tutorial or Training Content for [TOPIC/PRODUCT]",
      category: "Video/Audio",
      description:
        "Produce educational video content teaching how to use a product, complete a process, or learn a skill. This includes scripting, screen recording or filming, adding annotations, voice-over, and editing for clarity. Typically requested for customer onboarding, internal training, or educational content marketing. The VA should be able to break down complex topics into clear, step-by-step instructions.",
      keyConsiderations:
        "Keep videos focused and concise (under 10 minutes ideally). Use clear visuals and highlight important elements. Speak slowly and clearly in voice-overs. Add captions for accessibility. Test tutorial by having someone follow along.",
      subtasks: [
        "Outline tutorial content and learning objectives",
        "Write script or talking points",
        "Prepare demo environment or materials",
        "Record screen capture or video footage",
        "Record voice-over narration",
        "Edit video with annotations and highlights",
        "Add text overlays for key points",
        "Include intro/outro branding",
        "Add background music if appropriate",
        "Export with captions and final formatting",
      ],
      deliverables: [
        "Tutorial script or outline",
        "Final edited tutorial video",
        "Captions/subtitle file (SRT)",
        "Thumbnail image for video",
        "Supplementary written guide if requested",
        "Video chapter markers",
        "Multiple resolution exports",
        "Upload to learning platform or YouTube",
      ],
      qualityControlChecklist: [
        "Content is accurate and up-to-date",
        "Steps are clear and easy to follow",
        "Screen recordings are high quality",
        "Voice-over is clear and well-paced",
        "Important elements properly highlighted",
        "Text is legible at all video sizes",
        "Captions are accurate and synchronized",
        "Video tested with target audience",
        "No confidential information visible",
        "Client approved for publication",
      ],
    },

    // --- Automation (4) ---
    {
      title: "Build [AUTOMATION WORKFLOW] Using [TOOL/PLATFORM]",
      category: "Automation",
      description:
        "Design and implement an automated workflow using tools like Zapier, Make, n8n, or custom scripts. This includes mapping the process, setting up triggers and actions, testing the flow, and documenting how it works. Typical workflows include lead capture to CRM, email notifications, data syncing, or social media scheduling. Requested when clients want to reduce manual work and improve efficiency. The VA should understand automation logic and the platforms involved.",
      keyConsiderations:
        "Map the entire workflow before building. Test with real data but in a safe environment. Set up error notifications so failures don't go unnoticed. Document the workflow clearly for troubleshooting and future updates.",
      subtasks: [
        "Map current manual process and pain points",
        "Identify trigger events and desired actions",
        "Choose appropriate automation platform",
        "Connect required apps and authenticate",
        "Build workflow with triggers and actions",
        "Add filters and conditional logic if needed",
        "Set up error handling and notifications",
        "Test workflow with sample data",
        "Monitor initial runs and fix issues",
        "Document workflow and provide training",
      ],
      deliverables: [
        "Workflow diagram or process map",
        "Configured automation in platform",
        "Test results showing successful runs",
        "Error handling and notification setup",
        "Documentation of how workflow works",
        "Troubleshooting guide for common issues",
        "Access credentials securely documented",
        "Training video or guide for client",
        "List of connected apps and permissions",
        "Maintenance and monitoring plan",
      ],
      qualityControlChecklist: [
        "Workflow triggers reliably on specified events",
        "All actions execute as intended",
        "Data maps correctly between systems",
        "Error notifications are working",
        "No duplicate or missed records",
        "Workflow handles edge cases appropriately",
        "Connected apps have proper permissions",
        "Documentation is clear and complete",
        "Client understands how to monitor",
        "Backup or manual process documented",
      ],
    },
    {
      title: "Sync Data Between [SOURCE] and [DESTINATION] with [TOOL]",
      category: "Automation",
      description:
        "Design and implement a one-way or two-way data sync between two systems (e.g., form to CRM, e-commerce to email, spreadsheet to database) using an automation tool or API. Includes mapping fields, handling duplicates, scheduling, and error handling. Requested when teams use multiple tools and need data to stay in sync. The VA should understand both systems and the chosen sync method.",
      keyConsiderations:
        "Define source of truth to avoid conflicts. Map fields accurately and handle missing data. Test with sample data first. Set up alerts for failed runs. Document sync logic and schedule.",
      subtasks: [
        "Document source and destination schemas",
        "Define field mappings and rules",
        "Choose sync method (native, Zapier, API)",
        "Build and test sync (staging if possible)",
        "Handle duplicates and edge cases",
        "Schedule or trigger sync",
        "Monitor first runs and fix issues",
        "Document and hand off to client",
      ],
      deliverables: [
        "Working sync configuration",
        "Field mapping document",
        "Error handling and alert setup",
        "Short runbook for client",
      ],
      qualityControlChecklist: [
        "Data flows correctly both ways (if applicable)",
        "No unintended overwrites",
        "Errors trigger notifications",
        "Client can verify data in destination",
      ],
    },
    {
      title: "Create Automated Reporting System for [METRICS/DATA]",
      category: "Automation",
      description:
        "Build an automated system that pulls data from multiple sources, processes it, and generates regular reports without manual intervention. This includes connecting to data sources, creating templates, scheduling runs, and delivering reports via email or dashboard. Typically requested for recurring reporting needs like weekly sales reports, monthly analytics, or daily operations summaries. The VA should understand data connections, basic data transformation, and reporting tools.",
      keyConsiderations:
        "Ensure data accuracy by validating sources. Schedule reports for times when data is complete and fresh. Design templates that are easy to read and action-oriented. Set up failure alerts if report generation fails. Allow for manual report generation when needed.",
      subtasks: [
        "Identify all required data sources",
        "Map metrics and calculations needed",
        "Connect to data sources with credentials",
        "Create report template with visualizations",
        "Build data transformation logic",
        "Set up automated scheduling",
        "Configure email delivery or dashboard access",
        "Test with historical data",
        "Set up error monitoring and alerts",
        "Document system for maintenance",
      ],
      deliverables: [
        "Connected data sources",
        "Report template with branding",
        "Automated schedule configuration",
        "Email delivery setup or dashboard link",
        "Sample report output",
        "Data source documentation",
        "Troubleshooting guide",
        "Manual run instructions",
      ],
      qualityControlChecklist: [
        "All data sources connected reliably",
        "Metrics calculated accurately",
        "Report template is clear and actionable",
        "Schedule runs at optimal times",
        "Delivery method works consistently",
        "Error alerts configured properly",
        "Historical data validates correctly",
        "Client can access reports easily",
        "Documentation covers maintenance",
        "Backup plan exists for failures",
      ],
    },
    {
      title: "Set Up Automated Lead Nurture Sequence for [AUDIENCE/PRODUCT]",
      category: "Automation",
      description:
        "Create an automated email sequence that nurtures leads over time based on their actions and profile. This includes mapping the customer journey, writing email content, setting up triggers and timing, segmenting audiences, and tracking performance. Typically requested for onboarding new leads, re-engaging cold leads, or moving prospects through the sales funnel. The VA should understand email marketing automation and customer lifecycle.",
      keyConsiderations:
        "Personalize content based on lead behavior and attributes. Space emails appropriately (not too frequent). Include clear CTAs at each stage. Set up triggers for engagement and disengagement. Comply with email regulations and provide unsubscribe options.",
      subtasks: [
        "Map customer journey and touchpoints",
        "Define audience segments and criteria",
        "Write email copy for each sequence step",
        "Design email templates or use existing",
        "Set up automation triggers (signup, clicks, time)",
        "Configure delays between emails",
        "Add personalization and dynamic content",
        "Set up tracking and conversion goals",
        "Test sequence flow with test contacts",
        "Monitor and optimize based on performance",
      ],
      deliverables: [
        "Customer journey map",
        "Sequence flow diagram",
        "Email copy for all sequence steps",
        "Designed email templates",
        "Automation setup in platform",
        "Segmentation rules documented",
        "Tracking and goals configuration",
        "Performance dashboard or report setup",
        "Test results and screenshots",
        "Optimization recommendations",
      ],
      qualityControlChecklist: [
        "Journey map reflects actual customer path",
        "Emails provide value at each step",
        "Timing between emails is appropriate",
        "Triggers fire correctly based on actions",
        "Personalization works for all segments",
        "All links and CTAs functional",
        "Unsubscribe option in every email",
        "Sequence tested end-to-end",
        "Analytics tracking properly",
        "Client approved content and flow",
      ],
    },

    // --- Customer Support (4) ---
    {
      title: "Manage Customer Support Inbox and Respond to [CHANNEL] Inquiries",
      category: "Customer Support",
      description:
        "Monitor and respond to customer inquiries via email, chat, or ticketing system. This includes triaging requests, providing solutions, escalating complex issues, and maintaining customer satisfaction. Requires understanding of the client's products/services, tone of voice, and support policies. Typically requested by businesses needing consistent, timely customer communication. The VA should be empathetic, solution-oriented, and detail-focused.",
      keyConsiderations:
        "Respond within promised SLA timeframes. Maintain a helpful and empathetic tone. Know when to escalate vs. resolve independently. Track common issues to identify patterns. Protect customer data and privacy at all times.",
      subtasks: [
        "Review and triage incoming support requests",
        "Categorize and prioritize tickets by urgency",
        "Research solutions using knowledge base",
        "Respond with clear, helpful answers",
        "Escalate complex issues to appropriate team",
        "Follow up on pending or unresolved tickets",
        "Update customer records in CRM",
        "Document new issues for knowledge base",
        "Track response times and satisfaction",
        "Report common issues and trends to client",
      ],
      deliverables: [
        "Responded to all tickets within SLA",
        "Resolution documentation for each ticket",
        "Escalation log for complex issues",
        "Updated CRM records for customers",
        "New knowledge base articles if needed",
        "Daily or weekly support metrics report",
        "Common issues summary for client",
        "Customer satisfaction ratings",
        "Follow-up confirmations on resolved issues",
        "Recommendations for process improvements",
      ],
      qualityControlChecklist: [
        "All responses are within SLA timeframes",
        "Tone is friendly, professional, and on-brand",
        "Solutions are accurate and complete",
        "Escalations include full context",
        "No customer data exposed inappropriately",
        "Ticket statuses are up to date",
        "Follow-ups completed as promised",
        "Knowledge base is current",
        "Satisfaction scores meet targets",
        "Client briefed on any critical issues",
      ],
    },
    {
      title:
        "Create and Update Help Center Articles and FAQ for [PRODUCT/SERVICE]",
      category: "Customer Support",
      description:
        "Research common customer questions, draft or update help center articles and FAQs, organize content for findability, and optionally add screenshots or short videos. Reduces repeat inquiries and improves self-service. The VA should understand the product/service and write in clear, customer-friendly language.",
      keyConsiderations:
        "Write for the customer's reading level. Use consistent formatting and navigation. Keep content current as product changes. Include search-friendly titles and keywords. Link between related articles.",
      subtasks: [
        "Audit existing articles and support tickets",
        "Identify gaps and new topics",
        "Draft or revise articles with steps and examples",
        "Add or update FAQ entries",
        "Insert screenshots or media",
        "Organize categories and internal links",
        "Publish and set visibility",
        "Share with support team for feedback",
      ],
      deliverables: [
        "New or updated help articles",
        "Updated FAQ section",
        "Content map or index",
        "Handoff notes for future updates",
      ],
      qualityControlChecklist: [
        "Steps are accurate and testable",
        "No broken links or images",
        "Tone matches brand",
        "Search and navigation work",
      ],
    },
    {
      title: "Conduct Customer Satisfaction Survey and Analyze Results",
      category: "Customer Support",
      description:
        "Design, distribute, and analyze a customer satisfaction survey to gather feedback on products, services, or support experience. This includes creating survey questions, selecting distribution channels, collecting responses, analyzing data, and presenting insights with recommendations. Typically requested to measure NPS, identify improvement areas, or validate product changes. The VA should understand survey design best practices and basic data analysis.",
      keyConsiderations:
        "Keep surveys short and focused. Use a mix of quantitative and qualitative questions. Ensure anonymity when appropriate. Time surveys strategically (after purchase, support interaction). Act on feedback to close the loop with customers.",
      subtasks: [
        "Define survey goals and key questions",
        "Design survey with appropriate question types",
        "Set up survey in chosen platform",
        "Determine target audience and sample size",
        "Distribute survey via email, website, or app",
        "Monitor response rate and send reminders",
        "Close survey and export responses",
        "Analyze quantitative and qualitative data",
        "Identify trends and actionable insights",
        "Create summary report with recommendations",
      ],
      deliverables: [
        "Survey questions and design",
        "Survey link or distribution setup",
        "Response data export",
        "Quantitative analysis (scores, percentages)",
        "Qualitative themes from open responses",
        "Data visualizations (charts, graphs)",
        "Insights summary with key findings",
        "Recommendations for improvement",
        "Full analysis report",
      ],
      qualityControlChecklist: [
        "Questions are clear and unbiased",
        "Survey length is reasonable",
        "Distribution reached target audience",
        "Response rate meets minimum threshold",
        "Data analysis is accurate",
        "Insights are actionable and specific",
        "Recommendations prioritized by impact",
        "Confidentiality maintained for responses",
        "Report is clear and well-organized",
        "Client satisfied with findings",
      ],
    },
    {
      title: "Handle Product Returns and Refund Requests for [BUSINESS]",
      category: "Customer Support",
      description:
        "Process customer return and refund requests according to company policy. This includes reviewing requests, approving or denying based on criteria, coordinating logistics, processing refunds, updating records, and communicating with customers throughout. Typically requested for e-commerce businesses or service providers with refund policies. The VA should understand the refund policy thoroughly and handle sensitive situations diplomatically.",
      keyConsiderations:
        "Follow refund policy consistently and fairly. Respond quickly to minimize customer frustration. Gather information to understand root cause of returns. Process refunds promptly once approved. Use returns data to identify product or service issues.",
      subtasks: [
        "Review return/refund request details",
        "Verify purchase and eligibility per policy",
        "Communicate decision to customer clearly",
        "Coordinate return shipping if applicable",
        "Process refund in payment system",
        "Update order status in system",
        "Document reason for return",
        "Send confirmation to customer",
        "Track refund trends and patterns",
        "Report common return reasons to client",
      ],
      deliverables: [
        "Processed refund confirmations",
        "Updated order and customer records",
        "Return shipping labels if needed",
        "Customer communication log",
        "Return reason documentation",
        "Weekly or monthly returns report",
        "Trend analysis of return reasons",
        "Recommendations to reduce returns",
      ],
      qualityControlChecklist: [
        "Policy applied consistently to all requests",
        "Decisions made within SLA timeframe",
        "Customer communication is clear and empathetic",
        "Refunds processed accurately",
        "All records updated properly",
        "Return reasons documented for analysis",
        "Customer satisfaction maintained",
        "Escalations handled appropriately",
        "Trends identified and reported",
        "Client informed of any policy issues",
      ],
    },

    // --- Social Media (4) ---
    {
      title: "Manage [PLATFORM] Social Media Presence and Engagement",
      category: "Social Media",
      description:
        "Manage daily social media activities including posting content, engaging with followers, responding to comments and messages, and monitoring brand mentions. This includes content scheduling, community management, and performance tracking. Typically requested to maintain consistent social presence and build audience relationships. The VA should understand platform best practices, the client's brand voice, and how to handle various engagement scenarios.",
      keyConsiderations:
        "Post at optimal times for audience engagement. Respond to comments and messages promptly. Monitor for negative feedback or PR issues. Stay on-brand with all interactions. Track performance to inform content strategy.",
      subtasks: [
        "Schedule and publish approved content",
        "Monitor comments and mentions throughout day",
        "Respond to comments and direct messages",
        "Engage with relevant accounts and content",
        "Flag negative feedback or urgent issues",
        "Track engagement metrics daily",
        "Share user-generated content when appropriate",
        "Report trending topics or opportunities",
        "Update content calendar based on performance",
        "Compile weekly performance summary",
      ],
      deliverables: [
        "All scheduled posts published on time",
        "Response to all comments and messages",
        "Engagement activity log",
        "Escalation report for urgent issues",
        "User-generated content shares if applicable",
        "Daily engagement metrics",
        "Weekly performance report with insights",
        "Trending topics or opportunities identified",
        "Updated content calendar with learnings",
        "Recommendations for next week's content",
      ],
      qualityControlChecklist: [
        "All posts published at scheduled times",
        "No typos or broken links in posts",
        "Comments responded to within 24 hours",
        "Messages answered within SLA",
        "Negative feedback handled appropriately",
        "Brand voice maintained in all interactions",
        "Crisis situations escalated immediately",
        "Engagement metrics tracked accurately",
        "Performance trends identified",
        "Client kept informed of important interactions",
      ],
    },
    {
      title:
        "Create [MONTHLY/QUARTERLY] Social Media Content Calendar for [PLATFORMS]",
      category: "Social Media",
      description:
        "Plan a full content calendar for specified social platforms: themes, post types, copy, visual concepts, hashtags, and publish dates. Aligns with campaigns, product launches, or evergreen engagement. The VA should understand each platform's best practices and the client's brand voice and goals.",
      keyConsiderations:
        "Balance promotional and value-driven content. Respect platform algorithms and optimal posting times. Plan for holidays and key dates. Leave room for real-time or reactive posts. Ensure variety in format (image, video, carousel, etc.).",
      subtasks: [
        "Review goals, audience, and past performance",
        "Define content pillars and themes",
        "Draft post copy for each slot",
        "Suggest visual concepts or assets needed",
        "Assign dates and times per platform",
        "Add hashtags and CTAs",
        "Export calendar for client/scheduling tool",
        "Flag content that needs design or approval",
      ],
      deliverables: [
        "Content calendar (spreadsheet or tool)",
        "Post copy for all planned posts",
        "Hashtag and CTA list",
        "Asset request list for design team",
      ],
      qualityControlChecklist: [
        "No conflicting or duplicate themes",
        "Copy matches brand voice",
        "Dates and times are realistic",
        "Client can hand off to designer/scheduler",
      ],
    },
    {
      title: "Run Paid Social Media Ad Campaign for [OBJECTIVE]",
      category: "Social Media",
      description:
        "Plan, set up, and manage a paid advertising campaign on social platforms (Facebook, Instagram, LinkedIn, TikTok). This includes audience targeting, ad creative development, budget allocation, campaign setup, monitoring performance, and optimization. Typically requested for lead generation, brand awareness, or product launches. The VA should understand ads manager platforms, targeting options, and performance metrics.",
      keyConsiderations:
        "Define clear campaign objective aligned with business goals. Target narrow, relevant audiences to maximize efficiency. A/B test ad creative and copy. Monitor daily during launch period. Don't overspend on underperforming ads. Comply with platform advertising policies.",
      subtasks: [
        "Define campaign objective and KPIs",
        "Research and define target audiences",
        "Set campaign budget and bid strategy",
        "Create or coordinate ad creative assets",
        "Write compelling ad copy and headlines",
        "Set up campaign in ads manager",
        "Configure tracking pixels and conversions",
        "Launch campaign and monitor initial performance",
        "Optimize based on performance data",
        "Compile campaign performance report",
      ],
      deliverables: [
        "Campaign strategy document",
        "Audience targeting specifications",
        "Ad creative files and copy",
        "Campaign setup in ads manager",
        "Conversion tracking configuration",
        "Daily performance monitoring notes",
        "Mid-campaign optimization recommendations",
        "Final campaign performance report",
        "ROI and conversion analysis",
        "Recommendations for future campaigns",
      ],
      qualityControlChecklist: [
        "Campaign objective properly configured",
        "Targeting reaches intended audience",
        "Budget set correctly with daily limits",
        "Ad creative meets platform specifications",
        "Copy follows platform advertising policies",
        "Conversion tracking tested and working",
        "Campaign launched on scheduled date",
        "Performance monitored daily",
        "Underperforming ads paused or optimized",
        "Client updated on performance regularly",
      ],
    },
    {
      title: "Grow Social Media Following and Engagement for [PLATFORM]",
      category: "Social Media",
      description:
        "Implement organic growth strategies to increase followers and engagement on social media. This includes hashtag research, strategic following/engagement, content optimization, collaboration outreach, and community building tactics. Typically requested when building a new account or reviving a stagnant one. The VA should understand platform algorithms, growth tactics, and authentic engagement practices.",
      keyConsiderations:
        "Focus on attracting relevant, engaged followers, not just numbers. Use platform-compliant growth tactics only. Engage authentically, not through bots or spam. Build relationships with complementary accounts. Track quality metrics, not just follower count.",
      subtasks: [
        "Audit current account and identify opportunities",
        "Research relevant hashtags for discoverability",
        "Identify and engage with target audience accounts",
        "Optimize profile and bio for conversions",
        "Create engagement-optimized content",
        "Initiate conversations and build relationships",
        "Collaborate with complementary accounts",
        "Run engagement campaigns or challenges",
        "Track growth and engagement metrics",
        "Report on progress and refine strategy",
      ],
      deliverables: [
        "Account audit with growth opportunities",
        "Hashtag strategy and research",
        "Target account list for engagement",
        "Optimized profile and bio",
        "Engagement-focused content plan",
        "Collaboration outreach messages",
        "Weekly growth metrics report",
        "Audience quality analysis",
        "Strategy refinements based on data",
      ],
      qualityControlChecklist: [
        "Growth tactics comply with platform rules",
        "Engagement is authentic and valuable",
        "Follower growth is steady and sustainable",
        "Engagement rate improving alongside follower count",
        "Audience quality verified (real, relevant followers)",
        "Profile optimized for target audience",
        "Content resonating with community",
        "No spam or automated tactics used",
        "Client satisfied with growth quality",
        "Strategy adapted based on results",
      ],
    },

    // --- Analytics (4) ---
    {
      title: "Create [PERFORMANCE] Analytics Report and Dashboard",
      category: "Analytics",
      description:
        "Collect, analyze, and visualize data to create a comprehensive performance report or dashboard. This includes setting up tracking, pulling data from various sources, identifying trends, and presenting insights with recommendations. Typical use cases include website analytics, marketing campaign performance, sales metrics, or social media analytics. Requested when clients need data-driven insights to make decisions. The VA should be comfortable with analytics tools and data interpretation.",
      keyConsiderations:
        "Ensure data accuracy by verifying sources and calculation methods. Focus on actionable insights, not just raw numbers. Visualize data clearly for easy understanding. Protect sensitive business data. Set up recurring reports to track changes over time.",
      subtasks: [
        "Define key metrics and KPIs to track",
        "Set up or verify tracking implementation",
        "Connect data sources to reporting tool",
        "Pull data for specified time period",
        "Clean and validate data accuracy",
        "Calculate key metrics and trends",
        "Create visualizations (charts, graphs)",
        "Analyze patterns and identify insights",
        "Write summary with recommendations",
        "Deliver report and set up automated refresh",
      ],
      deliverables: [
        "KPI definition document",
        "Data source connection documentation",
        "Raw data export if requested",
        "Visual dashboard or report",
        "Key metrics summary",
        "Trend analysis with period comparisons",
        "Charts and graphs for key data points",
        "Written insights and recommendations",
        "Automated report setup if applicable",
        "Next steps and optimization suggestions",
      ],
      qualityControlChecklist: [
        "All data sources connected correctly",
        "Tracking verified for accuracy",
        "Calculations and formulas are correct",
        "Date ranges and filters applied properly",
        "Visualizations are clear and accurate",
        "Insights are data-driven and actionable",
        "No sensitive data exposed inappropriately",
        "Report format meets client preferences",
        "Automated refresh working if set up",
        "Client understands how to read and use report",
      ],
    },
    {
      title: "Set Up Conversion Tracking and Funnels for [WEBSITE/CAMPAIGN]",
      category: "Analytics",
      description:
        "Implement conversion tracking (e.g., Google Analytics 4, Meta Pixel, LinkedIn Insight Tag) and define key funnels (e.g., signup, purchase, lead). Includes tag installation, event configuration, funnel setup, and verification. Requested when launching new campaigns or sites, or when existing tracking is incomplete. The VA should be familiar with tag managers and analytics platforms.",
      keyConsiderations:
        "Use a tag manager (e.g., GTM) where possible for flexibility. Respect consent and privacy (cookie banners, consent mode). Test events in debug mode before going live. Document what is tracked and where for the client.",
      subtasks: [
        "Audit current tracking setup",
        "Define conversion events and funnels",
        "Create tags and triggers in tag manager",
        "Install or verify base tags (GA4, etc.)",
        "Configure conversion events",
        "Set up funnel steps in analytics",
        "Test in staging or with debug tools",
        "Document implementation for client",
        "Verify data in reports after launch",
      ],
      deliverables: [
        "Tracking implementation (tags/GTM)",
        "Conversion and funnel documentation",
        "Test/verification report",
        "Short guide for viewing in analytics",
      ],
      qualityControlChecklist: [
        "Key events fire correctly",
        "Funnels reflect actual user flow",
        "No duplicate or missing tags",
        "Privacy/consent considered",
        "Client can see data in dashboard",
      ],
    },
    {
      title: "Conduct A/B Test for [WEBPAGE/EMAIL/AD]",
      category: "Analytics",
      description:
        "Design, implement, and analyze an A/B test to compare two or more variants and determine which performs better. This includes hypothesis formation, variant creation, sample size calculation, test setup, monitoring, and statistical analysis of results. Typically requested to optimize conversion rates, engagement, or revenue. The VA should understand testing methodology, statistical significance, and experiment design.",
      keyConsiderations:
        "Test one variable at a time for clear results. Run test until statistically significant sample is reached. Don't call tests early or cherry-pick results. Consider external factors that might skew results. Implement winning variant and document learnings.",
      subtasks: [
        "Define hypothesis and success metric",
        "Identify variable to test (headline, CTA, etc.)",
        "Create test variants (A and B)",
        "Calculate required sample size",
        "Set up test in platform (website, email, ads)",
        "Configure even traffic split",
        "Launch test and monitor for issues",
        "Wait for statistical significance",
        "Analyze results and declare winner",
        "Document findings and implement winner",
      ],
      deliverables: [
        "Test hypothesis document",
        "Variant designs or copy",
        "Sample size calculation",
        "Test setup confirmation",
        "Performance monitoring log",
        "Statistical analysis of results",
        "Winner declaration with confidence level",
        "Test results summary report",
        "Implementation plan for winning variant",
        "Learnings and next test recommendations",
      ],
      qualityControlChecklist: [
        "Hypothesis clearly stated and testable",
        "Only one variable changed between variants",
        "Sample size sufficient for significance",
        "Traffic split evenly between variants",
        "Test ran for appropriate duration",
        "External factors documented",
        "Results reached statistical significance",
        "Analysis methodology is sound",
        "Winner implemented correctly",
        "Learnings documented for future tests",
      ],
    },
    {
      title: "Audit and Improve [ANALYTICS] Data Quality and Accuracy",
      category: "Analytics",
      description:
        "Review existing analytics implementation to identify and fix tracking issues, data discrepancies, or configuration errors. This includes auditing tracking code, validating data accuracy, fixing broken tags, removing spam traffic, and documenting data quality improvements. Typically requested when data seems incorrect or unreliable. The VA should have deep knowledge of analytics platforms and debugging skills.",
      keyConsiderations:
        "Document all current issues before fixing anything. Test fixes in staging environment when possible. Verify that fixes don't break existing tracking. Compare data across platforms to validate accuracy. Implement ongoing monitoring to catch future issues.",
      subtasks: [
        "Audit current analytics implementation",
        "Identify tracking gaps and errors",
        "Document data discrepancies found",
        "Check for spam or bot traffic",
        "Review tag configuration in tag manager",
        "Test all conversion tracking",
        "Fix identified issues systematically",
        "Set up filters to exclude spam traffic",
        "Validate data accuracy post-fix",
        "Create monitoring alerts for future issues",
      ],
      deliverables: [
        "Analytics audit report with issues found",
        "Data discrepancy documentation",
        "Fixed tracking implementation",
        "Spam filter configuration",
        "Validation test results",
        "Before/after data comparison",
        "Updated tracking documentation",
        "Monitoring alerts setup",
        "Best practices guide",
        "Maintenance recommendations",
      ],
      qualityControlChecklist: [
        "All major tracking issues identified",
        "Fixes implemented without breaking existing tracking",
        "Data accuracy validated across platforms",
        "Spam traffic properly filtered",
        "Conversion tracking works correctly",
        "Cross-domain tracking functioning if needed",
        "Data matches expectations",
        "Documentation updated to reflect changes",
        "Monitoring in place to catch future issues",
        "Client confident in data reliability",
      ],
    },
  ];
}
