import { FormConfig } from "./jdFormConfig";

export const businessBrainFormConfig: FormConfig = {
  storageKey: "business-brain-form-data",
  title: "Set Up Your AI Business Brain",
  description:
    "Tell us about your business so your AI assistant can learn, remember, and generate content for you.",
  sections: [
    {
      id: "business-snapshot",
      title: "Business Snapshot",
      description: "Core business information",
      fields: [
        {
          id: "legalName",
          label: "Legal Business Name",
          type: "text",
          placeholder: "Acme Inc. LLC",
          required: true,
          helpText: "Your official registered business name",
        },
        {
          id: "publicName",
          label: "Public/Trade Name (if different)",
          type: "text",
          placeholder: "Acme",
          helpText: "The name customers know you by, if different from legal name",
        },
        {
          id: "website",
          label: "Website URL",
          type: "text",
          placeholder: "https://example.com",
          required: true,
          helpText: "Your company website",
        },
        {
          id: "offers",
          label: "Primary Offers (up to 3)",
          type: "textarea",
          placeholder: "Example:\n• Virtual Assistant Services - Administrative support for busy entrepreneurs\n• Social Media Management - Complete content creation and scheduling\n• Customer Support - 24/7 customer service handling",
          required: true,
          helpText: "List your top 3 offers with a 1-sentence description each",
        },
        {
          id: "outcomePromise",
          label: "Primary Outcome Promise",
          type: "text",
          placeholder: "Get 20+ hours back every week with a dedicated VA",
          required: true,
          helpText: "One sentence describing the main transformation you deliver (compliance-safe)",
        },
        {
          id: "pricing",
          label: "Pricing Model",
          type: "text",
          placeholder: "$500-1500/month or 'custom'",
          required: true,
          helpText: "Price range or pricing approach",
        },
        {
          id: "primaryCTA",
          label: "Primary CTA",
          type: "select",
          options: [
            { label: "Book a Call", value: "book_call" },
            { label: "Buy Now", value: "buy_now" },
            { label: "Request Quote", value: "request_quote" },
            { label: "Get Started", value: "get_started" },
            { label: "Schedule Demo", value: "schedule_demo" },
            { label: "Custom", value: "custom" },
          ],
          required: true,
          helpText: "Your primary call-to-action",
        },
        {
          id: "customCTA",
          label: "Custom CTA Text",
          type: "text",
          placeholder: "Your custom CTA",
          showIf: { field: "primaryCTA", value: "custom" },
          helpText: "Enter your custom CTA text",
        },
        {
          id: "geography",
          label: "Geography Served",
          type: "text",
          placeholder: "Remote (US/Canada) or specific cities/regions",
          required: true,
          helpText: "Where do you serve customers?",
        },
      ],
    },
    {
      id: "audience-positioning",
      title: "Audience & Positioning",
      description: "Who you serve and how you position yourself",
      fields: [
        {
          id: "icps",
          label: "Ideal Customer Profiles (max 3)",
          type: "repeater",
          maxItems: 3,
          itemFields: [
            {
              id: "segment",
              label: "Role/Segment",
              type: "text",
              placeholder: "e.g., Women 30-55, Tech Founders, Small Business Owners",
              required: true,
            },
            {
              id: "pain",
              label: "Primary Pain Point",
              type: "text",
              placeholder: "e.g., Overwhelmed with admin tasks",
              required: true,
            },
            {
              id: "outcome",
              label: "Desired Outcome",
              type: "text",
              placeholder: "e.g., Focus on growth instead of operations",
              required: true,
            },
          ],
          required: true,
          helpText: "Define your ideal customers with their pain points and desired outcomes",
        },
        {
          id: "objections",
          label: "Top 3 Objections",
          type: "textarea",
          placeholder: "1. Too expensive\n2. Worried about quality of remote work\n3. Don't want to train someone new",
          required: true,
          helpText: "What are the most common objections you hear?",
        },
        {
          id: "topCompetitor",
          label: "#1 Competitor",
          type: "text",
          placeholder: "e.g., Freelance marketplaces or in-house hiring",
          required: true,
          helpText: "Your main competitor or alternative solution",
        },
        {
          id: "competitors",
          label: "Other Competitors & Differentiation",
          type: "textarea",
          placeholder: "How do you differentiate from other options?",
          helpText: "What makes you different from alternatives?",
        },
      ],
    },
    {
      id: "brand-voice",
      title: "Brand Voice Quick-Read",
      description: "Adjust sliders to define your brand personality",
      fields: [
        {
          id: "formalCasual",
          label: "Formal ↔ Casual",
          type: "slider",
          required: true,
          helpText: "1 = Very Formal, 5 = Very Casual",
        },
        {
          id: "playfulSerious",
          label: "Playful ↔ Serious",
          type: "slider",
          required: true,
          helpText: "1 = Very Playful, 5 = Very Serious",
        },
        {
          id: "directStoryDriven",
          label: "Direct ↔ Story-driven",
          type: "slider",
          required: true,
          helpText: "1 = Very Direct, 5 = Very Story-driven",
        },
        {
          id: "punchyDetailed",
          label: "Punchy ↔ Detailed",
          type: "slider",
          required: true,
          helpText: "1 = Very Punchy/Concise, 5 = Very Detailed",
        },
        {
          id: "inspirationalAnalytical",
          label: "Inspirational ↔ Analytical",
          type: "slider",
          required: true,
          helpText: "1 = Very Inspirational, 5 = Very Analytical",
        },
        {
          id: "soundsLike",
          label: "Sound Most Like",
          type: "text",
          placeholder: "e.g., Apple Support tone, Mailchimp, Gary Vee",
          required: true,
          helpText: "Name 2-3 public brands or people whose voice you want to emulate",
        },
      ],
    },
    {
      id: "proof-compliance",
      title: "Proof & Compliance",
      description: "Legal requirements and proof assets",
      fields: [
        {
          id: "hasProofAssets",
          label: "Do you have proof assets available?",
          type: "select",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
          required: true,
        },
        {
          id: "proofAssetsList",
          label: "List Your Proof Assets",
          type: "textarea",
          placeholder: "• Case study: 50% time savings for tech startup\n• Testimonial from Jane Doe\n• Metric: 95% client satisfaction rate",
          showIf: { field: "hasProofAssets", value: "yes" },
          helpText: "List available case studies, testimonials, or metrics",
        },
        {
          id: "forbiddenWords",
          label: "Forbidden Words/Claims",
          type: "textarea",
          placeholder: "guaranteed, 100% success, never",
          required: true,
          helpText: "Comma-separated list of words or claims to never use",
        },
        {
          id: "disclaimers",
          label: "Required Disclaimers",
          type: "textarea",
          placeholder: "Results may vary. Individual results not guaranteed.",
          required: true,
          helpText: "Paste exact legal disclaimers that must appear in content",
        },
        {
          id: "isRegulated",
          label: "Regulated Industry?",
          type: "select",
          options: [
            { label: "No", value: "no" },
            { label: "Yes", value: "yes" },
          ],
          required: true,
        },
        {
          id: "regulatedIndustryType",
          label: "Which Industry?",
          type: "select",
          options: [
            { label: "Medical", value: "medical" },
            { label: "Financial", value: "financial" },
            { label: "Legal", value: "legal" },
            { label: "Real Estate", value: "real_estate" },
            { label: "Education", value: "education" },
            { label: "Other", value: "other" },
          ],
          showIf: { field: "isRegulated", value: "yes" },
          required: true,
        },
      ],
    },
    {
      id: "ops-tools",
      title: "Ops & Tools",
      description: "Optional but powerful for implementation",
      fields: [
        {
          id: "crmPlatform",
          label: "CRM Platform",
          type: "text",
          placeholder: "GoHighLevel, HubSpot, Salesforce, etc.",
          helpText: "What CRM do you use?",
        },
        {
          id: "crmSubaccount",
          label: "GoHighLevel Subaccount Name",
          type: "text",
          placeholder: "My Company GHL",
          helpText: "If using GoHighLevel, what's your subaccount name?",
        },
        {
          id: "pipelineStages",
          label: "Sales Pipeline Stages",
          type: "textarea",
          placeholder: "Engaged Inquiry → Call Requested → Scheduled → Showed → Deciding → Won → Lost",
          helpText: "Paste your pipeline stages or accept defaults",
        },
        {
          id: "supportEmail",
          label: "Support Email",
          type: "text",
          placeholder: "support@example.com",
          helpText: "Your support/contact email",
        },
        {
          id: "emailSignoff",
          label: "Email Sign-off",
          type: "text",
          placeholder: "—The Acme Team",
          helpText: "How do you sign off on emails?",
        },
        {
          id: "meetingLink",
          label: "Meeting Link",
          type: "text",
          placeholder: "https://calendly.com/yourname",
          helpText: "Calendly or booking link",
        },
        {
          id: "brandEmails",
          label: "Brand Domain Emails",
          type: "text",
          placeholder: "hello@, support@, sales@",
          helpText: "List your brand email addresses",
        },
      ],
    },
    {
      id: "content-samples",
      title: "Content Samples",
      description: "Optional but high leverage for voice calibration",
      fields: [
        {
          id: "favoriteParagraphs",
          label: "Favorite Brand Paragraphs",
          type: "textarea",
          placeholder: "Paste 2-3 examples of content you love that matches your brand voice",
          helpText: "Examples of your best writing",
        },
        {
          id: "avoidParagraphs",
          label: "Absolutely Not Examples",
          type: "textarea",
          placeholder: "Paste 2-3 examples of tone/style to avoid",
          helpText: "Examples of what NOT to sound like",
        },
        {
          id: "contentLinks",
          label: "Content Links",
          type: "textarea",
          placeholder: "Links to blog posts, social profiles, or other content examples",
          helpText: "URLs to your existing content",
        },
      ],
    },
    {
      id: "file-uploads",
      title: "Files & Links",
      description: "Upload brand assets and documentation",
      fields: [
        {
          id: "logo",
          label: "Logo (SVG/PNG)",
          type: "file",
          fileConfig: {
            maxSize: 5 * 1024 * 1024,
            allowedExtensions: [".png", ".jpg", ".jpeg", ".svg"],
            allowedMimeTypes: ["image/png", "image/jpeg", "image/svg+xml"],
          },
          helpText: "Upload your company logo",
        },
        {
          id: "brandGuide",
          label: "Brand Guide (PDF)",
          type: "file",
          fileConfig: {
            maxSize: 10 * 1024 * 1024,
            allowedExtensions: [".pdf", ".doc", ".docx"],
            allowedMimeTypes: [
              "application/pdf",
              "application/msword",
              "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            ],
          },
          helpText: "Brand guide with colors, fonts, style rules",
        },
        {
          id: "writingSamples",
          label: "Writing Samples",
          type: "file",
          fileConfig: {
            maxSize: 10 * 1024 * 1024,
            allowedExtensions: [".pdf", ".doc", ".docx", ".txt"],
            allowedMimeTypes: [
              "application/pdf",
              "application/msword",
              "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
              "text/plain",
            ],
          },
          helpText: "3 'yes' examples + 3 'nope' examples",
        },
        {
          id: "proofDocuments",
          label: "Proof Assets (Case Studies, Testimonials)",
          type: "file",
          fileConfig: {
            maxSize: 10 * 1024 * 1024,
            allowedExtensions: [".pdf", ".doc", ".docx", ".txt"],
            allowedMimeTypes: [
              "application/pdf",
              "application/msword",
              "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
              "text/plain",
            ],
          },
          helpText: "Case studies, testimonials, or results screenshots",
        },
        {
          id: "sops",
          label: "SOPs (Top 3)",
          type: "file",
          fileConfig: {
            maxSize: 10 * 1024 * 1024,
            allowedExtensions: [".pdf", ".doc", ".docx", ".txt"],
            allowedMimeTypes: [
              "application/pdf",
              "application/msword",
              "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
              "text/plain",
            ],
          },
          helpText: "Your top 3 SOPs (Intake → Nurture → Book → Close → Onboard)",
        },
        {
          id: "ghlTemplates",
          label: "GHL Templates/Snapshots",
          type: "file",
          fileConfig: {
            maxSize: 10 * 1024 * 1024,
            allowedExtensions: [".pdf", ".doc", ".docx", ".txt"],
            allowedMimeTypes: [
              "application/pdf",
              "application/msword",
              "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
              "text/plain",
            ],
          },
          helpText: "Pipeline stages, snapshot notes, existing templates",
        },
      ],
    },
    {
      id: "guardrails",
      title: "Guardrails",
      description: "Optional constraints and escalation rules",
      fields: [
        {
          id: "avoidTopics",
          label: "Topics We Never Talk About",
          type: "textarea",
          placeholder: "Politics, religion, controversial social issues",
          helpText: "Topics that are off-limits for your brand",
        },
        {
          id: "avoidCompetitors",
          label: "Competitors We Never Mention",
          type: "textarea",
          placeholder: "Company X, Company Y",
          helpText: "Competitors you don't want referenced",
        },
        {
          id: "escalationContact",
          label: "Escalation: Who Approves Risky Copy?",
          type: "text",
          placeholder: "name@example.com",
          helpText: "Who should approve sensitive or risky content?",
        },
      ],
    },
  ],
  defaultValues: {
    legalName: "",
    publicName: "",
    website: "",
    offers: "",
    outcomePromise: "",
    pricing: "",
    primaryCTA: "",
    customCTA: "",
    geography: "",
    icps: [],
    objections: "",
    topCompetitor: "",
    competitors: "",
    formalCasual: 50,
    playfulSerious: 50,
    directStoryDriven: 50,
    punchyDetailed: 50,
    inspirationalAnalytical: 50,
    soundsLike: "",
    hasProofAssets: "",
    proofAssetsList: "",
    forbiddenWords: "",
    disclaimers: "",
    isRegulated: "",
    regulatedIndustryType: "",
    crmPlatform: "",
    crmSubaccount: "",
    pipelineStages: "",
    supportEmail: "",
    emailSignoff: "",
    meetingLink: "",
    brandEmails: "",
    favoriteParagraphs: "",
    avoidParagraphs: "",
    contentLinks: "",
    avoidTopics: "",
    avoidCompetitors: "",
    escalationContact: "",
  },
  submitButtonText: "Generate Business Brain",
  apiEndpoint: "/api/business-brain/analyze",
};